# -*- coding: utf-8 -*-
"""pattern2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hyM8pMmtKpz1NxdkNmekZgzZiTEWcDqy
"""

# Floyd’s Triangle
# 1
# 2 3
# 4 5 6
# 7 8 9 10
# 11 12 13 14 15
rows = 5
num = 1
for i in range(1,rows+1):
  for j in range(1,i+1):
    print(num,end=" ")
    num+=1
  print()

# Binary Number Triangle
# 1
# 0 1
# 0 1 0
# 1 0 1 0
# 1 0 1 0 1
rows = 5  # Total lines

for i in range(1, rows + 1):  # i = current line number
    # Step 1: Decide starting number
    if i % 2 == 0:
        val = 0   # Even line → start with 0
    else:
        val = 1   # Odd line → start with 1

    # Step 2: Print numbers in the line
    for j in range(1, i + 1):  # Print i numbers
        print(val, end=" ")
        val = 1 - val  # Flip the value (1 becomes 0, 0 becomes 1)

    print()  # Move to next line

# Hollow Square / Hollow Box
# * * * * *
# *       *
# *       *
# *       *
# * * * * *
n = 5                    # Size of box
for i in range(1,n+1):   #row loop
  for j in range(1,n+1): #column loop
    if i==1 or i==n or j == 1 or j ==n:
      print("*",end=" ")
    else:
      print(" ",end=" ")
  print()

n=int(input("enter the n:"))
for i in range(1,n+1):
  for j in range(1,n+1):
    if i == 1 or i == n or j == 1 or j == n:
      print("*",end = " ")
    else:
      print(" ",end = " ")
  print()

# Butterfly Pattern(half)
# *       *
# * *     * *
# * * *   * * *
# * * * * * * *
n = 4
for i in range(1,n+1):
  for j in range(1, i+1):
    print("*",end = " ")

  for s in range(2 * (n-i)):
    print(" ",end="")

  for j in range(1,i+1):
    print("*",end = " ")
  print()

# full butterfly
# *       *
# * *     * *
# * * *   * * *
# * * * * * * * *
# * * * * * * * *
# * * *   * * *
# * *     * *
# *       *
n=4
#for upper part
for i in range(1,n+1):
  for j in range(1,i+1):
    print("*",end = " ")

  spaces = 2*(n-i)
  for s in range(spaces):
    print(" ",end = "")

  for j in range(1,i+1):
    print("*",end=" ")
  print()
#for lower part
for i in range(n,0,-1):
  for j in range(1,i+1):
    print("*",end=" ")

  spaces = (2*(n-i))
  for s in range(spaces):
    print(" ",end="")

  for j in range(1,i+1):
    print("*",end=" ")
  print()

# hour glass
n = 3
for i in range(n):
  print(" "*i,end=" ")
  print("* "*(n-i))
for i in range(1,n):
  print(" " * (n-i-1) ,end=" ")
  print("* " * (i+1))

#  Pascal’s Triangle (Star Format)
#         *
#       * *
#     * * *
#   * * * *
# * * * * *
n = 5

for i in range(1, n + 1):
    # Spaces before stars
    print("  " * (n - i), end="")  # 2 spaces per gap for alignment

    # Stars
    print("* " * i)