# -*- coding: utf-8 -*-
"""array_logical_ques.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GWPsHmYt4enTZOJn-LaeplL5PtVRqB18
"""

# Q1. Find the Maximum Element in Array
arr = [12,4,5,34,65]
max = arr[0]

for i in arr:
  if i > max:
    max = i
print(max) #output = 65

# Q2. Reverse the Array
arr = [12,22,33,44,54,43]
arr.reverse()
print(arr)  #output = [43,54,44,33,22,12]

# Method 2 (manual)
rev = []
for i in range(len(arr)-1, -1, -1):
  rev.append(arr[i])
print(arr)  #output: [43, 54, 44, 33, 22, 12]

# Q3. Sum of All Elements
arr = [12,2,34,56,67]
total = 0
for i in arr:
  total += i
print(total) #171

# Q4. Check if Element Exists
arr = [10, 20, 30]
x = 20
if x in arr:
  print("yes")
else:
  print("no")

# Find the minimum element in an array.
arr = [12,3 ,4,54,6,7]
min = arr[0]

for i in arr:
  if i < min:
    min = i
print(min) #3

# count even numbers in array
arr = [2,3,4,5,6,7,8]
count = 0

for i in arr:
  if i % 2 == 0:
    count += 1
print("total even numbers in array: ",count)   #total even numbers in array:  4

# average of elements
arr = [21,23,4,56]
sum = 0

for i in arr:
  sum += i
average = sum / len(arr)
print("average is : ",average)  #average is :  26.0

# Find duplicates in array
arr = [1,2,3,4,5,2,3,7,1]
freq = {}

for i in arr:
  if i in freq:
    freq[i] += 1
  else:
    freq[i] = 1
print("duplicate values:")
for keys in freq:
  if freq[keys] > 1:
    print(keys)
# output:
duplicate values:
1
2
3

