# -*- coding: utf-8 -*-
"""Arrays.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d5Bpsa5-hLZdQy0ceG55cuaxHs_lKvLK
"""

#array in python are container which stores multiple values as same data types.
#moslt work done by list

arr = [10,20,30,40]

# Basic Array Operations
# 1. Traverse / Print all elements
arr = [10, 20, 30, 40]
for i in arr:
  print(i)

#output
10
20
30
40

# 2. Accessing Elements (Indexing)
print(arr[0])
print(arr[-2])
print(arr[2])

# output
10
30
30

# 3. Update an element
arr[2]=77
print(arr)

# output
[10, 20, 77, 40]

# 4. Insert at End (append)
arr.append(56)
print(arr)

# output
[10, 20, 77, 40, 56]

# 5. Insert at Any Index
arr.insert(3,44)
print(arr)

# 44 placed at 3rd index
[10, 20, 77, 44, 40, 56]

# 6. Delete an Element
arr.remove(77)
print(arr)
# output
[10, 20, 44, 40, 56]