# -*- coding: utf-8 -*-
"""linear_search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PzUqAetX9QN0i8OuUeo8CP7D3xi1mYlH
"""

linear search is a technique where we check ever element in array one by one.

when to use:
when array is unsorted and data is small

# logic:
for i in range(len(arr)):
  if arr[i] == target:
    return i   #index of target

#example:
# we have to search for 30 which is in index 2
arr = [10, 20, 30, 40, 50]
target = 30

arr = [10,20,30,40,50]
target = 30

found = False       #suppose there is no 30
for i in range(len(arr)):
  if arr[i] == target:    #if elements of array equals to target
    print("found at index",i)
    found = True
    break                  #then we break the loop
if not found:
  print("not found") #output: found at index 2

time complexity:
o(1): if first element is matched #best case
o(n): if last element is matched or not #worst case

#search for 60 in this array
arr = [10,20,30,40,50,60]
target = 60

found = False
for i in range(len(arr)):
  if arr[i] == target:
    print("found at index",i)
    found = True
    break
if not found:
  print("not found") #output: found at index 5

arr = [11,22,33,44,55,66]
target = 11

found = False

for i in range(len(arr)):
  if arr[i] == target:
    print("found at index", i)
    found = True
    break
if not found:
  print("not found")
#output
#found at index 0