# -*- coding: utf-8 -*-
"""list_comprehension.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EHxEZlZmN69hpjIZpS9T57dcQ3amLbsY
"""

#list creation
numbers = [1, 2, 3, 4, 5]
fruits = ["apple", "banana", "mango"]
mixed = [10, "hello", True]

#accessing elements
#indexing always start from 0
print(numbers[0])   # 1
print(fruits[2])    # mango
print(mixed[1])     # hello

#list slicing
print(numbers[1:3])
print(mixed[1:])
print(fruits[0:])

#modifying list
fruits[0]= "cake"
print(fruits)

# looping through list
for fruit in fruits:
  print(fruit)

# checking membership
if "cake" in fruits:
  print("yes")

# list comprehension
squares = [x**2 for x in range (1,6)]
print(squares)

numbers = [21,3,4,56,78]
total = sum(numbers)
print(total)

numbers = [10, 20, 30, 40, 50]
total = sum(numbers)
print("Sum =", total)

nums = [1,2,3,4,5,6,7,8,9]
for n in nums:
  if n%2 ==0:
    print(n)

score = [23,4,56,78,65,54,3]
score.sort(reverse=True)
print(score)

# remove duplicate from list
numbers = [2,2,3,4,3,5,1,2,1]
unique = list(set(numbers))
print(unique)

# list comprehension
num = [i**2 for i in range(1,5)]
print(num)

even = [i for i in range(1,10) if i % 2 ==0]  #printing even numbers
print(even)

names = ["deepak","sagar","dhruv","sachin","harsh"] # uppercase
upper = [name.upper() for name in names]
print(upper)

# square of even numbers
squares = [x**2 for x in range(1,15) if x%2 == 0]
print(squares)

# get first letter
fruits = ["apple","banana","lichi","mango"]
first_letter = [fruit[0] for fruit in fruits]
print(first_letter)