# -*- coding: utf-8 -*-
"""anagram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HotPa1ASw8np0IT0vMTyOJBWk1jtb-ky
"""

# Anagram: Two strings are anagrams if they contain the same characters, in same frequency, but possibly in different order.
# Examples:

# "listen" and "silent" → ✅ Anagram

# "hello" and "world" → ❌ Not an anagram

# "triangle" and "integral" → ✅ Anagram

# logic:
# take two strings
# remove spaces
# lower them
# sort them
# if sorted is same then it is anagram

# s1 = "listen"
# s2 = "silent"

# sorted(s1) = ['e', 'i', 'l', 'n', 's', 't']
# sorted(s2) = ['e', 'i', 'l', 'n', 's', 't']

# ✅ Both same → It's an Anagram

def is_anagram(s1,s2):

  s1 = s1.replace(" ","").lower()
  s2 = s2.replace(" ","").lower()

  return sorted(s1) == sorted(s2)

s1 = input("enter the string: ")
s2 = input("enter the string: ")

if is_anagram(s1,s2):
  print("anagram")
else:
  print("not anagram")