# -*- coding: utf-8 -*-
"""count_vowel_consonents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NuHqhuHLez4AI7P0N8dTEblPR5mVi03S
"""

Problem:
Given a string, count:

Total vowels

Total consonants

🔸 Vowels = a, e, i, o, u (ignore case)
🔸 Consonants = all alphabets except vowels

Logic:
Input string .

Convert it to lowercase.

check every character:

if vowel → vowel_count += 1

if alphabet (but not vowel) → consonant_count += 1

Digits, symbols, spaces ignore

def count_vowels_consonants(s):
    vowels = "aeiou"
    vowel_count = 0
    consonant_count = 0

    for char in s.lower():         # lowercase convert
        if char.isalpha():         # only check alphabets
            if char in vowels:     # is it vowel?
                vowel_count += 1
            else:
                consonant_count += 1  # if not vowel, but alphabet → consonant

    return vowel_count, consonant_count

# Input
string = input("Enter a string: ")

# Call the function
vowels, consonants = count_vowels_consonants(string)

# Output
print(f"Vowels: {vowels}")
print(f"Consonants: {consonants}")