# -*- coding: utf-8 -*-
"""is_palindrome_string.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oexpXQKlhLHlu053gb3ItWj7N376ttMC
"""

A string is a palindrome if it reads the same forward and backward.

"madam" → ✅ Palindrome

"hello" → ❌ Not a palindrome

"racecar" → ✅ Palindrome

logic :
take a string
reverse it
compare to original or reversed string
if same return true else false

# dry run
Input: "level"

Original string = "level"
Reversed string = "level"

Check: "level" == "level" → ✅ Palindrome

def check_palindrome(s):
  #reverse the string
  reversed = s[::-1]
  # comparing
  if s == reversed:
    return True
  else:
    return False
# testing

string = input("enter the string: ")
if check_palindrome(string):
  print("yes it is palindrome")
else:
  print("its not palindrome")

# Ignore Case & Spaces (Advanced Interview Variant)
def is_palindrome(s):
  s = s.replace(" ","").lower()  #remove space and convert to lowerspace
  return s == s[::-1]
#test
string = input("enter the string: ")
if is_palindrome(string):
  print("yes its palindrome")
else:
  print("no its not!")